#Source file for components used by the compiler.

#innertext property is for inner text of the component.
#id property is for the id generated by the compiler.
#parent property is for the parent component of the component.

components = {
    "text": {
        "attributes": {},
        "component": f'''        
        #id = Gtk.Label()
        #id.set_text(#innertext)
        #parent_id.append(#id)'''
    },
    "box": {
        "attributes": {},
        "component": f'''
        #id = Gtk.Box()
        #parent_id.append(#id)'''
    },
    "button": {
        "attributes": {
            "onclick": {
                "#string": f'''
                #id.connect('clicked', #string)
                '''
            }
        },
        "component": f'''
        #id = Gtk.Button(label=#innertext)
        #parent_id.append(#id)'''
    },
}